<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__exchange_rate</name>
   <tag></tag>
   <elementGuidId>0ee619f0-7331-47d7-af64-f4744cd3fa64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exchange_rate_show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exchange_rate_show']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input Exchange Rate...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd4b215-8407-4b2a-a045-63f054b82701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>exchange_rate form-control form-control-solid  </value>
      <webElementGuid>43758b14-ac62-42fd-9e73-7d2f1b7cd009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>06749f22-7e3f-429d-a4b5-feb0965b9d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exchange_rate_show</value>
      <webElementGuid>2d3e8a34-8174-45b0-81c7-cc7817da3327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input Exchange Rate...</value>
      <webElementGuid>fe5311f9-8384-4cd9-accb-dc4a45d77c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>3ae2fbbd-34d7-4e9f-9dcc-202fc385ee55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exchange_rate</value>
      <webElementGuid>fdfa38f2-974b-4f35-bbf1-3327daee11ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>134e8ab2-da75-4e64-be9c-97e310318bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exchange_rate_show&quot;)</value>
      <webElementGuid>0f14f498-fa5c-48b2-ac1d-5e02678dc25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exchange_rate_show']</value>
      <webElementGuid>e057868c-fd8c-4716-be45-e55e65d69966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='exchange_rates']/div/div/div[2]/div[4]/input</value>
      <webElementGuid>ae947cd7-e7a1-4119-91f1-896ff65536b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>95177901-ed3c-4b6a-8db4-177af959bc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exchange_rate_show' and @placeholder = 'Fill input Exchange Rate...' and @name = 'exchange_rate' and @type = 'text']</value>
      <webElementGuid>7d2700e8-633e-4b8e-a0cd-1402d486c608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
