<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RMB</name>
   <tag></tag>
   <elementGuidId>abf3d18c-dcb5-405d-8daf-c3032f04ef3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='purchase_request']/div/div/div[2]/div[3]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap5.select2-container--above.select2-container--focus.select2-container--open > span.selection > span.select2-selection.select2-selection--single.col-md-6.form-select.form-select-solid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;RMB&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21bd015e-88f6-43ac-a833-0a0b23d57ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single col-md-6 form-select form-select-solid</value>
      <webElementGuid>5ea9049c-2117-4cdc-9c4d-e962a886a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>facce2a8-dacf-4d00-8c25-519a8ddf5ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>34835cfc-a914-4d39-b49f-ffc66ecb0725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>46651114-8833-4b19-9bdc-5a1943441c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec59c96e-5e02-48aa-bc2c-e1a2e993a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51c3f8b3-caf5-4f7d-a08b-1ecac9d68d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-currency-container</value>
      <webElementGuid>0afeabc1-9546-435f-87c8-c8e489decf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-currency-container</value>
      <webElementGuid>deeba548-d49e-4c46-8f1f-23f0127d7d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-currency-results</value>
      <webElementGuid>2ed235ca-6ee4-4b6c-8d06-cfe9669a3aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>select2-currency-result-80tz-RMB</value>
      <webElementGuid>6d03251b-cfc1-4db4-a0c6-5d892e2de807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RMB</value>
      <webElementGuid>e539289a-8862-447e-ac93-c68791b43cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase_request&quot;)/div[@class=&quot;card mb-10&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row content-tab-home mt-4&quot;]/div[@class=&quot;col-md-6 d-flex flex-column mb-9 fv-row box_currency&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--above select2-container--focus select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single col-md-6 form-select form-select-solid&quot;]</value>
      <webElementGuid>70d4c367-6bb1-45dc-96c4-7cea5754fb60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='purchase_request']/div/div/div[2]/div[3]/span/span/span</value>
      <webElementGuid>bfe2e0a1-56a7-4de3-95ed-3d7c53283fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[3]</value>
      <webElementGuid>826d1bfb-0ef9-4129-84d7-2055aa4067fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span</value>
      <webElementGuid>8d6e3fde-0917-49ed-b7d2-5036a647034e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'RMB' or . = 'RMB')]</value>
      <webElementGuid>84604916-62d1-402a-8be3-6c9165b81153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
