<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pr_reff_</name>
   <tag></tag>
   <elementGuidId>78b3007e-a8ed-415c-ad84-9b1f4588b816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pr_reff_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pr_reff_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input PR Reff...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f2cff71-6d02-4062-8042-00d261de1f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid  is-invalid</value>
      <webElementGuid>db78b935-59a2-4185-9520-a59bc490a267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>09b441e6-43ff-4f04-a63c-d8bedd26bf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pr_reff_text</value>
      <webElementGuid>5eea7e85-72b1-4508-8a52-856c6fddb9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input PR Reff...</value>
      <webElementGuid>167dc633-cc5d-4f01-a047-594e03350bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>3134b37f-ccf4-4f7b-9877-c4ee33bb1514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pr_reff_text</value>
      <webElementGuid>75bdf398-e577-4bde-bfe3-ae4f83a2ae12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6f9325a-744a-41ce-b700-88e9479cb9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_reff_text&quot;)</value>
      <webElementGuid>78a2eb44-07d3-4104-a1f0-0417b459bc30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pr_reff_text']</value>
      <webElementGuid>08d98973-fe15-41e8-a043-a6fb56805db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='purchase_order']/div/div/div[2]/div[3]/input[2]</value>
      <webElementGuid>98e88fec-3d7d-4082-8b2b-167f272f1a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>63e8946b-b9fb-4f9c-b994-9ccf25f6b54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pr_reff_text' and @placeholder = 'Fill input PR Reff...' and @name = 'pr_reff_text' and @type = 'text']</value>
      <webElementGuid>275601ab-0772-48fd-90a2-342ac7f9e5cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
