<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_qty_PR_ref_oa</name>
   <tag></tag>
   <elementGuidId>deb3e87e-7591-4ae7-a943-6df4ca5093c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#po_detail_qty_1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='po_detail_qty_1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input Qty...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5399318-3914-4c0a-89ed-eb61c0637b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid po-detail-qty is-invalid</value>
      <webElementGuid>2f95cc87-faa3-454e-b961-82b90fee7b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input Qty...</value>
      <webElementGuid>7cbf7054-1830-4977-bdbc-506dc6368397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>po_detail_qty[0][0]</value>
      <webElementGuid>f8087338-577b-4985-8252-8907489d4a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5796d0b8-5caf-4a77-b252-2a93a3304ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>po_detail_qty_1_0</value>
      <webElementGuid>e0c03811-416d-4b8a-a400-d2f9f30c1ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de6ec725-f046-4c3f-86f1-9b77b0b4bd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>beba3b42-d521-4764-aeff-fe4545481362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>d002ba75-febc-4de8-bdde-a1e15d2d2564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;po_detail_qty_1_0&quot;)</value>
      <webElementGuid>72b95570-b72c-444d-bd73-7837745ccb8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='po_detail_qty_1_0']</value>
      <webElementGuid>ea2c00d5-ad8a-4f5a-9ef5-9605e9de8782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_search_pr_reff_1']/tbody/tr/td[5]/input</value>
      <webElementGuid>3f796c34-d923-4c2c-bcbf-dee4f09efe10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>eafbdd7b-d83b-424b-ad43-c588559b79e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Fill input Qty...' and @name = 'po_detail_qty[0][0]' and @type = 'number' and @id = 'po_detail_qty_1_0']</value>
      <webElementGuid>5bcabf18-e01a-420f-80bd-bfae19679476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
