<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__delivery_date_PO_OA</name>
   <tag></tag>
   <elementGuidId>a9256af9-4536-40e4-a9fe-5d5b751a6b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delivery_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delivery_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Select a date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9784149-c3ac-4de9-ba5d-2c490c581478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>91ff940b-bb84-4289-8a3d-94a514004dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delivery_date</value>
      <webElementGuid>85eb50b4-b4fc-4804-964c-124a5ceb2e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 date_123</value>
      <webElementGuid>d331b0f2-68f7-46c3-b151-a0d2b61cd466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>37898613-6f53-408b-8154-1f3d70a5b3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>delivery_date</value>
      <webElementGuid>309e79a1-4301-403b-bb6a-bd4fb1439abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delivery_date&quot;)</value>
      <webElementGuid>74107b17-5720-42d1-ae16-3c3f94ed6f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delivery_date']</value>
      <webElementGuid>b92f0998-6b8a-4b0c-872f-b0ac1b6bf799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_add_item_scroll']/div/div/div/div[6]/div/input</value>
      <webElementGuid>aa35275c-eb43-40c8-90ec-1bff366825fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>57fabd98-e9a7-4bca-a060-933be15fc967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'delivery_date' and @placeholder = 'Select a date' and @name = 'delivery_date']</value>
      <webElementGuid>1932c1ca-e28c-4a71-a0ba-74bd4ce970b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
