<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supporting Document_supporting_document</name>
   <tag></tag>
   <elementGuidId>66ba00d6-b15b-44b0-8273-0a66309acb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supporting_document_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supporting_document_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#supporting_document_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24e9b190-f1a8-4262-8375-6d0aaa9d4a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d2fd82b3-04f3-4351-bab8-71efccf15c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input</value>
      <webElementGuid>720af104-6a99-4e39-bf0a-3bb3ed6b1b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supporting_document[]</value>
      <webElementGuid>d208bb93-2fa2-46f3-ba6a-ad29ea68fd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supporting_document_1</value>
      <webElementGuid>aa87611b-57f8-4c80-b8f7-687b7a5dd3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supporting_document_1&quot;)</value>
      <webElementGuid>d41ea928-041c-4c76-92a0-68ac215ab4de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supporting_document_1']</value>
      <webElementGuid>3ceff26f-4089-4237-916f-d811d12e9189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_supporting_document_1']/div/div/input</value>
      <webElementGuid>89a376bf-556f-4e4e-9565-0c2ffcae15c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/input</value>
      <webElementGuid>a122bded-039b-4dff-824e-6a70824f479e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'supporting_document[]' and @id = 'supporting_document_1']</value>
      <webElementGuid>b4dfbf70-e09e-4541-bc3c-5a44e7e20ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
