<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ManageLeave</name>
   <tag></tag>
   <elementGuidId>63136920-9277-4121-917c-d798d2248bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-PERSONAL']/li[5]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Manage Leave&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a9d56a4-57ca-4a0b-93f2-f006a9883c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-16o9nsd</value>
      <webElementGuid>f42fefef-2ce5-4aa5-9ffe-04681155ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Leave</value>
      <webElementGuid>8f4abf09-85b7-444a-9fc5-b334d2df9b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-PERSONAL&quot;)/li[@class=&quot;css-18jz1pp&quot;]/div[@class=&quot;css-167s026&quot;]/a[@class=&quot;css-ml9k47&quot;]/span[@class=&quot;css-16o9nsd&quot;]</value>
      <webElementGuid>0a19313b-945a-4228-bf34-e9021c4554c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-PERSONAL']/li[5]/div/a/span</value>
      <webElementGuid>a2a7cb44-8aaf-46db-a95d-99a31b03f455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Information'])[1]/following::span[1]</value>
      <webElementGuid>0d60973b-03f9-465e-9edc-c14bc6b435e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites'])[3]/following::span[2]</value>
      <webElementGuid>770de902-23f9-4f23-9428-abcc78b2dbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses Hub'])[1]/preceding::span[1]</value>
      <webElementGuid>5fa1ee4b-674b-482b-984b-42d9f4aca52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journeys'])[1]/preceding::span[2]</value>
      <webElementGuid>93389530-9090-4fc0-bd38-7ae128f65c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Leave']/parent::*</value>
      <webElementGuid>2538e7c9-5bdc-4c7a-86ed-99b00cc54158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a/span</value>
      <webElementGuid>64516c2c-96ed-42f8-bf68-85f0eb971c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Manage Leave' or . = 'Manage Leave')]</value>
      <webElementGuid>66fbae28-7af1-4d03-b270-9cce4cd431f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
