<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__submission_date</name>
   <tag></tag>
   <elementGuidId>aed4788c-edad-470d-8e5a-a44f871970fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submission_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submission_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#submission_date</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bc51878-074f-4a6f-97a9-6daee289c922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8fa090a6-e7ab-4f7e-88f7-88a32cd360dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submission_date</value>
      <webElementGuid>1c5b04a3-e45d-4cca-9573-79cd626049dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2024-03-18</value>
      <webElementGuid>dbb0a147-988d-4fce-8727-1616b18bcc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 date_123 </value>
      <webElementGuid>18046d22-8077-4363-b983-d6ffdd0783db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>9db42186-6d64-4e81-82f8-779aedf60396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submission_date</value>
      <webElementGuid>d0b06db5-4631-4581-b98d-d2f3ca206fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submission_date&quot;)</value>
      <webElementGuid>3d931c32-2e5a-46c1-b254-33ad29bf3864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submission_date']</value>
      <webElementGuid>27c93f23-f9ec-4c64-9342-5899cb19237d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='purchase_request']/div/div/div/div[6]/div/input</value>
      <webElementGuid>9150d13b-9423-4983-8c35-10c14e8fdbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>f68fe7cb-942b-493c-b264-5e8aea81dab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'submission_date' and @placeholder = 'Select a date' and @name = 'submission_date']</value>
      <webElementGuid>296b2a86-afde-4489-b7b9-4faf49cd36eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
