<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UR Number_ur_number</name>
   <tag></tag>
   <elementGuidId>8b9084b7-d7dc-4490-909c-4578f8d8c8f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ur_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ur_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input UR Number...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3014524f-33ee-48cd-aa14-520e8dc3d278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid  </value>
      <webElementGuid>4cf0e307-6f24-4354-8685-9e8d7c45ee24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f90fcbcf-a503-47d3-88fc-35de8239fe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ur_number</value>
      <webElementGuid>2baa219d-238f-46fe-97a3-d6e277babf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input UR Number...</value>
      <webElementGuid>00cb85ea-a995-48b4-a9fd-0bbf83c43377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>9570f0ab-5207-4bc6-9735-d2084491114b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>67856809-9f9c-4333-813c-b791ae45dccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ur_number</value>
      <webElementGuid>c3c5c805-cde0-437e-ac60-9be849b68db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13e6d59e-b0a1-476b-953e-f78c89589fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ur_number&quot;)</value>
      <webElementGuid>a38c9ce9-e2a4-4cc7-a8c7-ec27fece72e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ur_number']</value>
      <webElementGuid>a008000c-e7a7-4f2e-a5d4-374656dc7ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_add_item_scroll']/div/div/div/div/input</value>
      <webElementGuid>aba6ece1-c9ab-4af1-9612-42ea2d30d26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/input</value>
      <webElementGuid>30a27f84-7fca-4c4f-bcc4-d290cbcd2b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ur_number' and @placeholder = 'Fill input UR Number...' and @name = 'ur_number' and @type = 'text']</value>
      <webElementGuid>52c86cd8-014d-45c0-bb51-2b9c11cc3da8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
