<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Updated At_updated_at</name>
   <tag></tag>
   <elementGuidId>e00be20e-0c7d-49b0-92b6-5c677f5f1e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#updated_at</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='updated_at']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#updated_at</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fafabe85-c7b7-4875-af01-1f54751807fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5aaef6e-e3ba-4095-88b6-ecd0dd76c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updated_at</value>
      <webElementGuid>327afa26-18ec-44a6-b905-1c6491e53cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 </value>
      <webElementGuid>59df3874-acfa-475e-89ea-b4e352ac2cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>140b6d3b-5c13-4d94-aac5-48777ed1cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updated_at</value>
      <webElementGuid>0f6330f6-1388-4861-b2e5-32f079dcc851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>e7d96727-3c0a-433d-8eb0-ac44b63b7344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updated_at&quot;)</value>
      <webElementGuid>9f77972b-290c-46e4-9513-73aa52aee54f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='updated_at']</value>
      <webElementGuid>89739f19-5880-4a63-8121-930e999ba410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_add_item_scroll']/div/div/div/div[17]/div/input</value>
      <webElementGuid>dd65b46e-88bd-4bef-90ab-a3265592aa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/input</value>
      <webElementGuid>f3974771-40fb-4a87-9a48-0c624cdd5154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'updated_at' and @placeholder = 'Select a date' and @name = 'updated_at']</value>
      <webElementGuid>416bf0e4-8ba1-468c-b287-b86c1de3136d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
