<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO Number_po_number</name>
   <tag></tag>
   <elementGuidId>adb6a43a-aa4a-439c-b3e1-66cbf74484ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#po_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='po_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input PO Number...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bad1a0c-ff47-40ec-81ce-b9ae461113cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid  </value>
      <webElementGuid>18e93d50-7ee4-42cd-96e5-c14636a0fd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b40652ec-2ff2-4ee7-a823-ec3f7f8cd79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>po_number</value>
      <webElementGuid>d64e7efc-434a-43f9-b514-ba4ae4d30749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input PO Number...</value>
      <webElementGuid>b0806b29-108b-459f-b83d-e09124f7c049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>93151006-3975-447e-b7b3-18c4e9bfc2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-id</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c28c4e63-b49d-447e-a39b-c52a15dc0513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>po_number</value>
      <webElementGuid>b0ecbee0-329d-4256-b3b7-cb40cf392c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac0ab48b-f119-42b8-8f4a-76149ca56bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;po_number&quot;)</value>
      <webElementGuid>372e5fd4-c05e-4592-b9e3-336d383e1ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='po_number']</value>
      <webElementGuid>7256ee58-aed4-4c89-8694-ae19fdc759c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_add_item_scroll']/div/div/div/div[15]/input</value>
      <webElementGuid>31b7aba5-2d14-48b7-8f49-433d74e7c3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/input</value>
      <webElementGuid>95a9b9a9-3059-4818-9d3d-1c94c1a05898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'po_number' and @placeholder = 'Fill input PO Number...' and @name = 'po_number' and @type = 'text']</value>
      <webElementGuid>ad46c47a-fa3b-4006-a7f2-1e07cdfa753a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
