<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__posting_date</name>
   <tag></tag>
   <elementGuidId>ceca9459-d637-46bb-aa1e-674c64d8b24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='posting_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#posting_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#posting_date</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b588e4a-a2c0-4b8d-9812-68129b14cf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>ca1696eb-b331-4715-adbd-6cfb8fa84915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>posting_date</value>
      <webElementGuid>615f8abf-1fd8-422f-b547-5990836efa55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 date_123 </value>
      <webElementGuid>9042db13-403d-49f4-b814-c92bbabb2704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>4cf33d1e-a2fd-4936-a3f6-b0d14b411398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>posting_date</value>
      <webElementGuid>6028af4a-7445-413f-a6da-3cbf47e1fe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;posting_date&quot;)</value>
      <webElementGuid>dde0736f-907e-426b-a580-4a54585ace7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='posting_date']</value>
      <webElementGuid>9a1593b8-a4a2-4a4b-9756-1e301de4f659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='good_receipt']/div/div/div[2]/div[5]/div/input</value>
      <webElementGuid>b4c78d28-c9f2-4c1b-9991-0afec234b1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>3801829e-335c-4eeb-b674-d97f6c0cdad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'posting_date' and @placeholder = 'Select a date' and @name = 'posting_date']</value>
      <webElementGuid>603df96e-7526-439f-bd7c-55e1f1dd7f60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
