<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Dokumen_name0</name>
   <tag></tag>
   <elementGuidId>471eeb97-ab63-4c71-b836-65aa009ffe33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d54a5c0a-e8a8-4274-a7d9-cc88ce9bbde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid validate-hidden name</value>
      <webElementGuid>a767a89c-bfd6-41df-b1b7-14e48bb54ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f476321b-adeb-4358-b201-b7ff0addd3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name_1</value>
      <webElementGuid>b2edf92e-d91b-42ad-a238-d6937beea810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Dokumen</value>
      <webElementGuid>33aeab3b-8290-4fe8-9645-6a853ed4fdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name[0]</value>
      <webElementGuid>8c81997e-7ecc-4b4a-81e9-675ad7a3d141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af289b31-24fe-4364-bbe4-434768411be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nama Tes SITU12</value>
      <webElementGuid>485685ad-da6f-425d-a999-fd971b7c07f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_1&quot;)</value>
      <webElementGuid>54561786-2b8c-4e43-96f6-1d776316a86b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name_1']</value>
      <webElementGuid>79baae82-4576-47ff-b491-4a9f34ade11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>961ca1f7-ac2d-45d3-bb67-293206ffba80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>8723dd05-f6ce-4d25-865c-fe6cbd082750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'name_1' and @placeholder = 'Nama Dokumen' and @name = 'name[0]' and @type = 'text']</value>
      <webElementGuid>f43e612c-71ce-44ac-a47d-a086146dbee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
