<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SK. Menkumham No_no_sk_menkumham0</name>
   <tag></tag>
   <elementGuidId>55d279e0-71db-4760-9a3e-2b6b1415b179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_sk_menkumham_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_sk_menkumham_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>768d6063-f71a-42b5-a5d4-8fdf9b3e6c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid validate-hidden no_sk_menkumham</value>
      <webElementGuid>d5fc902a-a2e7-43c2-a0b1-36d449286800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>71767e56-d992-4b98-b03d-136772ea8a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_sk_menkumham_1</value>
      <webElementGuid>cd41dc92-c989-457a-a23f-a4af2fbd871f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SK. Menkumham No</value>
      <webElementGuid>b03941df-6c51-4289-a69a-2ed181094c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_sk_menkumham[0]</value>
      <webElementGuid>b533050d-a465-47be-9f67-1c2ba23efa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8287ef46-5801-4b0c-8cba-1b0d698484b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1231131313</value>
      <webElementGuid>035834f1-c657-4f80-be6a-f3d6e4c388ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_sk_menkumham_1&quot;)</value>
      <webElementGuid>58482a67-6017-4642-8e22-54a37ca515d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_sk_menkumham_1']</value>
      <webElementGuid>0a6bd05a-27a0-4aa1-9cb1-0c1072f52ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>ca52ccd7-c358-4c5a-9b63-2fa9c036df8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>b682a4ef-6d9d-47a7-863e-636cb3438934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_sk_menkumham_1' and @placeholder = 'SK. Menkumham No' and @name = 'no_sk_menkumham[0]' and @type = 'text']</value>
      <webElementGuid>9dbbe969-4423-4429-b709-d10267ca7439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
