<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dikeluarkan Oleh_published_by0</name>
   <tag></tag>
   <elementGuidId>989eabce-5f70-4cac-b5e5-837528a6ba3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='published_by_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#published_by_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3a5f7e-c15f-4b1a-bf6a-dfebe6b15f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid validate-hidden published_by</value>
      <webElementGuid>84f71f72-7c8c-496f-996c-bd7f9a56d44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>35dce9d1-9684-404c-945d-ba8326e4a4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>published_by_1</value>
      <webElementGuid>b079b9f5-c2de-4332-9d8c-3c75508fd429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dikeluarkan Oleh</value>
      <webElementGuid>c9afa36b-076f-4185-a043-7c5b467140a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>published_by[0]</value>
      <webElementGuid>629da1ae-001a-48cc-afde-b2fe1b241b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55ecddfd-2ef5-441c-af31-fbd1b8097f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>PT ABC123</value>
      <webElementGuid>9453565f-e289-414e-bb34-c13abf031e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;published_by_1&quot;)</value>
      <webElementGuid>bda73682-9035-43f0-a163-e6f4189af3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='published_by_1']</value>
      <webElementGuid>6346c76a-d7d5-48dd-96b2-72dcf6fb437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>77679189-bab9-4683-ae1b-b9424caf1ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>b8f074df-caae-41e7-9b12-6acf390750c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'published_by_1' and @placeholder = 'Dikeluarkan Oleh' and @name = 'published_by[0]' and @type = 'text']</value>
      <webElementGuid>4d061876-e516-4b41-b7ee-5da6a8c097e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
