<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Akta_no_akta0</name>
   <tag></tag>
   <elementGuidId>2df71de8-0a39-4041-832b-ca9520de6340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_akta_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#no_akta_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>961825d1-e668-46ab-97aa-a88ad6ff565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid validate-hidden akta</value>
      <webElementGuid>272c61ce-90be-4c15-9727-aa1f8796cc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>9fba7c7a-9257-43c7-9b32-0d028b150fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_akta_1</value>
      <webElementGuid>b744c611-2490-4770-bd3c-982105ac6d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Akta</value>
      <webElementGuid>b3587824-cfb0-4bbb-9151-d89908606083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_akta[0]</value>
      <webElementGuid>584b6103-3326-44ad-8733-28c86695372e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f947aec5-1e08-4bf3-a419-7812c824d7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>213412913001390</value>
      <webElementGuid>ee7df89a-78a7-4b89-8163-b12a7702ac1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_akta_1&quot;)</value>
      <webElementGuid>94c9f48e-5344-49ac-bc0a-a6f16bc3628a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_akta_1']</value>
      <webElementGuid>3f8d098d-dbd2-40a6-8373-02fa349f580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>88dd998a-1782-49a3-a50d-3f6bedb24bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f3434f93-ef2b-4c51-810b-aa3fc86b9700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_akta_1' and @placeholder = 'Nomor Akta' and @name = 'no_akta[0]' and @type = 'text']</value>
      <webElementGuid>e1070c5e-9e75-40c9-82bf-ab9bc25d217e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
