<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tipe Perusahaan</name>
   <tag></tag>
   <elementGuidId>fc3fa3be-ad5b-445b-85fd-507060ea0583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-type_company-container']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection__placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tipe Perusahaan&quot;i >> internal:text=&quot;Tipe Perusahaan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67e26be0-8189-4a07-a7be-349f131282b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>3c5050a0-ba6a-4bd2-a251-f6cbed66df85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipe Perusahaan</value>
      <webElementGuid>cc67c969-4f2b-464e-91d2-45fd7a4256d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-type_company-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>5247da29-47c7-48f9-8d5c-7ee4f7183fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-type_company-container']/span</value>
      <webElementGuid>52661c90-6360-493d-8426-e92fbd6d2bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Perusahaan'])[1]/following::span[5]</value>
      <webElementGuid>7e5df47a-025b-419f-9945-5c0df4afd0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maks.: 10 MB jpg, jpeg, png, tiff'])[1]/following::span[5]</value>
      <webElementGuid>8d758473-4920-4d7a-8cd0-8a6187e005a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Rekanan'])[1]/preceding::span[3]</value>
      <webElementGuid>30644b3a-206d-4d28-a6b6-74aab573acbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Tipe Vendor'])[1]/preceding::span[3]</value>
      <webElementGuid>3a9bcd95-e8b6-4a2e-b372-3653db094092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>85e0e687-867d-4c6b-81d5-fc4704719451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tipe Perusahaan' or . = 'Tipe Perusahaan')]</value>
      <webElementGuid>882679d9-b7a7-4c69-ae59-ccc8a67a7a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
