<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_Status_term_of_payment</name>
   <tag></tag>
   <elementGuidId>aa886e0f-89c7-4ef0-9cef-121029b5c6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_modal_new_address_scroll']/div[5]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection.select2-selection--single.col-md-6.form-select.form-select-solid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Status...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a5d4407-fc50-4af4-b398-5b1afc71e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single col-md-6 form-select form-select-solid</value>
      <webElementGuid>62ccf3ff-4757-44b8-bcce-1f2ac4e6e71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4ea156e0-0a67-42b1-a253-fdd9663478ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac5861aa-1766-4bc5-810f-59ae74cd6e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b62ee30d-636c-49c2-b95b-6399bbf8dfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6aac697-1b08-4d53-aa3d-815b6ab41190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ab6a5936-a089-4fe1-971f-c8c8761351e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-status-container</value>
      <webElementGuid>8ff5bedc-31b4-4243-a3b1-af6fe01ec9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-status-container</value>
      <webElementGuid>abb5160a-acf3-4b2e-bf5b-b7ed595ca708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-status-results</value>
      <webElementGuid>7ab30e37-b660-47d0-8874-84b95a6a8e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>select2-status-result-hehf-A</value>
      <webElementGuid>e3c658cd-5fa0-41fa-99b8-272838abd4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Status...</value>
      <webElementGuid>364e771e-e22c-4c62-a0bd-761bf419ca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_new_address_scroll&quot;)/div[@class=&quot;col-md-6 d-flex flex-column mb-9 fv-row box_status&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--below select2-container--open select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single col-md-6 form-select form-select-solid&quot;]</value>
      <webElementGuid>22096a22-21bf-49e4-a49f-120017eed4c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_new_address_scroll']/div[5]/span/span/span</value>
      <webElementGuid>2326a259-82b6-4a01-8277-9cbc79c2bd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[3]</value>
      <webElementGuid>feb0ac18-c9b1-4f72-86eb-1716e00b523c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[5]</value>
      <webElementGuid>7e80a90e-4092-4c4e-b28e-6d210e9195c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/span/span/span</value>
      <webElementGuid>3d6a41b8-d921-43dc-9d68-244eca03a53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Status...' or . = 'Select Status...')]</value>
      <webElementGuid>f5d797c6-2b96-484d-8cc8-be220ca1ca6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
