<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_status_country</name>
   <tag></tag>
   <elementGuidId>1f1ab954-34f5-426a-a406-6a46dc367ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_modal_new_address_scroll']/div[4]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection.select2-selection--single.col-md-6.form-select.form-select-solid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Status...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05605f3e-fccb-4655-8212-4d019103574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single col-md-6 form-select form-select-solid</value>
      <webElementGuid>5d27b306-8bf6-43a9-9f7a-86e02c403f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>bc27a7c9-2557-4a18-b379-5c77d9eca828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7dca2621-f564-4f0d-b7a5-ba3afc526f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>829b4591-1900-4644-8e4a-ba4a1ca2e9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c9b9816-a9f7-4919-882d-11df084440d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55227a94-1c43-483c-8fcf-ee6e84d12985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-status-container</value>
      <webElementGuid>e48c16b7-163a-4422-bb91-5ef709b2bf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-status-container</value>
      <webElementGuid>a12388a6-4e63-4395-beb0-b8675643b0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-status-results</value>
      <webElementGuid>6aa67eb6-e85f-42ab-aafb-8962203e381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>select2-status-result-n2h1-A</value>
      <webElementGuid>a70c3fa1-282a-4322-b239-623c9acbf4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Status...</value>
      <webElementGuid>2cc14d43-a0e5-43f8-856a-be0976cb3437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_new_address_scroll&quot;)/div[@class=&quot;col-md-6 d-flex flex-column mb-9 fv-row box_status&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--below select2-container--open select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single col-md-6 form-select form-select-solid&quot;]</value>
      <webElementGuid>30d3c217-dbfe-423f-ba20-0922113b078b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_new_address_scroll']/div[4]/span/span/span</value>
      <webElementGuid>d0e2e413-aa40-4704-b8b0-13741f398213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[3]</value>
      <webElementGuid>9489ba51-8dd8-411d-aa42-85239e6b446b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[5]</value>
      <webElementGuid>053fb78e-a237-45c4-9ac2-b66b003ee713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/span/span/span</value>
      <webElementGuid>fd31fef3-0a0f-4ddb-b0b6-1f05c97c5fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Status...' or . = 'Select Status...')]</value>
      <webElementGuid>7f952d14-0631-4236-ae1b-72fc9dff5e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
