<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tax</name>
   <tag></tag>
   <elementGuidId>baf57443-3963-46fe-b980-8b3bbc38c7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu-sub.menu-sub-lg-down-accordion.menu-sub-lg-dropdown.menu-rounded-0.py-lg-4.w-lg-225px.show > div.menu-item.menu-lg-down-accordion.show.menu-dropdown > span.menu-link.py-3 > span.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#kt_header_menu']/div[3]/div/div[8]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Tax&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>675d166b-5e74-46f4-b368-ebfda29ac0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>59075e48-ba2b-447e-95d5-b7df7dde1119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tax</value>
      <webElementGuid>78f37062-91bc-4c80-b1f1-9e0d79f88e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#kt_header_menu&quot;)/div[@class=&quot;menu-item menu-lg-down-accordion me-lg-1 show menu-dropdown&quot;]/div[@class=&quot;menu-sub menu-sub-lg-down-accordion menu-sub-lg-dropdown menu-rounded-0 py-lg-4 w-lg-225px show&quot;]/div[@class=&quot;menu-item menu-lg-down-accordion show menu-dropdown&quot;]/span[@class=&quot;menu-link  py-3&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>59edca68-caf8-43bf-9066-c8709f65e238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#kt_header_menu']/div[3]/div/div[8]/span/span[2]</value>
      <webElementGuid>74bd4a45-5e7c-4a7a-8d20-cf7b8d1f19eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MoU'])[1]/following::span[5]</value>
      <webElementGuid>78b506c8-c313-4daf-9080-d69f0a796082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MoU OA'])[1]/following::span[9]</value>
      <webElementGuid>92e3f871-dfcb-475c-9a2f-3daef48ea519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPN'])[2]/preceding::span[4]</value>
      <webElementGuid>e3ac16e3-8288-4360-b62d-a8901a06f167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PPH'])[1]/preceding::span[7]</value>
      <webElementGuid>2fea051c-0759-4bcd-975a-eb286b21f8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tax']/parent::*</value>
      <webElementGuid>68df3dc4-52f5-455e-bc64-751375dee00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/span/span[2]</value>
      <webElementGuid>2ce5f337-3093-4a13-a359-71e21d4ddc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tax' or . = 'Tax')]</value>
      <webElementGuid>debbf05a-d173-477a-8f69-a2fa8622f176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
