<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kompetensi</name>
   <tag></tag>
   <elementGuidId>fde2f5d3-d29f-495d-822e-5ffd1bee0169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav_accordion']/li[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Kompetensi&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e874a69e-e404-4784-aabe-2ae5969648be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>9c4b95ea-96e2-459b-99ce-e213179d521c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>913f186a-6f91-4f55-9aa0-f2c1489cdd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://test-vendor.mmsgroup.co.id/company_profile/show/44ddbc64-be41-43d9-9206-5296e6a2b548/competence</value>
      <webElementGuid>c37d385c-538b-40ed-8069-727da803477d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Kompetensi
                                    </value>
      <webElementGuid>c1cbb23c-6e40-4082-81af-51ce606ace97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_accordion&quot;)/li[@class=&quot;nav-item has-submenu&quot;]/ul[@class=&quot;submenu collapse show&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>41dc1d6f-94c3-45dd-9972-4d72560c9d06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav_accordion']/li[2]/ul/li[2]/a</value>
      <webElementGuid>227f078a-08d9-4ad7-a115-2d14cedd933e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikasi'])[1]/following::a[1]</value>
      <webElementGuid>d1c1a7aa-e244-45a1-91a6-c713be45a308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kompetensi dan Pengalaman Kerja'])[1]/following::a[2]</value>
      <webElementGuid>6a06f9f5-bd01-4c84-b765-70b5986bb7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Keuangan'])[1]/preceding::a[1]</value>
      <webElementGuid>4ba83a7d-85a0-44f8-8582-e779a8d171f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://test-vendor.mmsgroup.co.id/company_profile/show/44ddbc64-be41-43d9-9206-5296e6a2b548/competence']</value>
      <webElementGuid>112b9a65-de69-4f7e-8fe3-8e780e6fb8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>d6021152-1676-48b1-9e3c-ca1afe1b63a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://test-vendor.mmsgroup.co.id/company_profile/show/44ddbc64-be41-43d9-9206-5296e6a2b548/competence' and (text() = '
                                        Kompetensi
                                    ' or . = '
                                        Kompetensi
                                    ')]</value>
      <webElementGuid>994af26b-6001-4a2a-b8e6-c770d79e586a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
