<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Valid_to</name>
   <tag></tag>
   <elementGuidId>a75754bb-1f52-4842-aad7-e5dcef7eda3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#valid_to_date_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='valid_to_date_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Berlaku Hingga Tanggal&quot;i] >> internal:attr=[placeholder=&quot;Select a date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc9eb0fa-4549-4c35-a7f8-4acfea5f8c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>27bd5764-8e17-4524-979d-1df2122ce096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>valid_to_date_1</value>
      <webElementGuid>4b9721cb-fc55-4f50-af46-a8ddec2bb963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 valid_to_date</value>
      <webElementGuid>958eeba6-2035-4852-8abd-2d39acf17784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>710aa49b-f479-4395-81c5-cdc269ec0528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>valid_to_date[0]</value>
      <webElementGuid>34eec0bb-a044-48c4-bc97-808c5f14fa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2028-03-01</value>
      <webElementGuid>070da397-e7f9-4523-bacd-72c3447bcfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;valid_to_date_1&quot;)</value>
      <webElementGuid>9871cf0a-a792-4f53-ab61-acbc01865ecc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='valid_to_date_1']</value>
      <webElementGuid>af7dc29b-8a8c-4176-98cd-780fb9b30095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>6da212b0-7723-4dd4-b21c-9cf17b69d9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/input</value>
      <webElementGuid>3db8b199-882f-4775-863a-149aa9b9147f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'valid_to_date_1' and @placeholder = 'Select a date' and @name = 'valid_to_date[0]']</value>
      <webElementGuid>46b43bc2-f792-46b8-827e-feddf9f0804b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
