<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Job Title</name>
   <tag></tag>
   <elementGuidId>7de4f1f4-f612-4db3-aab9-4d8e4f167fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2.select2-container.select2-container--bootstrap5.select2-container--above.select2-container--focus > span.selection > span.select2-selection.select2-selection--single.col-md-6.form-select.form-select-solid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='employee']/div/div/div/div[13]/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Job Title...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ffef0189-c260-4a8a-99ec-1a3e6e2ad97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single col-md-6 form-select form-select-solid</value>
      <webElementGuid>f6a9f8a0-afa1-4b75-ae74-52a4da7d3f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9876613c-eb34-4bda-b5d6-709b28e7f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99682884-6bcc-47c6-9d17-4c60709e4d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>554bad68-137e-4227-aa88-bd4405f77f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61cde2b0-7eb1-4a3c-ab41-938de2621e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e98d9032-ae1b-4e9e-a64d-0c4a4537beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-job_title-container</value>
      <webElementGuid>22fc9414-4e58-4ea9-9d7c-bb056b69e6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-job_title-container</value>
      <webElementGuid>7114ea8a-141c-4ea1-9ebd-0d65e5769259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Job Title...</value>
      <webElementGuid>67166681-983f-4e99-85b1-ef2d58fe4ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row content-tab-home mt-4&quot;]/div[@class=&quot;col-md-6 d-flex flex-column mb-9 fv-row box_job_title&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--above select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single col-md-6 form-select form-select-solid&quot;]</value>
      <webElementGuid>851d472a-8845-4415-a1fa-8b1cd37057d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='employee']/div/div/div/div[13]/span/span/span</value>
      <webElementGuid>c42ba361-3af7-4b65-9c91-63a753ee1b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::span[3]</value>
      <webElementGuid>031a2a4f-33eb-4f5e-8eb0-d9cd243459a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/span/span/span</value>
      <webElementGuid>8c662b00-8f05-497b-aa94-a646523d79b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Job Title...' or . = 'Select Job Title...')]</value>
      <webElementGuid>e3ba1067-c2b9-47eb-b4a2-6d3d96f6e59e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
