<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Phone_number</name>
   <tag></tag>
   <elementGuidId>ed6ee9ac-6d87-4207-b31d-0363c85cb08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no_telp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_telp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;No Telp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59f0d56a-279e-48ab-bb9f-31755b3a7351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid validate-hidden hide-arrow-phone </value>
      <webElementGuid>e8272f4b-712c-4658-b70c-4e6d23e4c8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>77611e68-9fa7-4aa3-924a-2882479c332a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_telp</value>
      <webElementGuid>2f0841ae-96e9-456c-8306-e79a4920b0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Telp</value>
      <webElementGuid>9e0a4058-2608-4ce3-9f9f-43529e8b4654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>d1a95d56-c041-47ff-a1d4-297001de2591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0c40a008-af49-40eb-892c-cf32174a5624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>5960d861-825d-42de-adb3-74b7c1b5e473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);</value>
      <webElementGuid>5971e982-75bf-4662-9bf4-7ed029a33047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_telp</value>
      <webElementGuid>15ffd4c9-8862-465d-a2ea-b8bce8e72111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ba180e18-62ee-4fcb-8aae-3abdb5009153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12993801011</value>
      <webElementGuid>369af872-43c6-4a83-a37f-12334b31e5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_telp&quot;)</value>
      <webElementGuid>e9eb47e8-b4e7-4b11-a79a-89787ecadc8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_telp']</value>
      <webElementGuid>7a3634e9-e3a2-4e3b-9f75-c49beeaa8387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table']/tbody/tr[9]/td[2]/div/div/input</value>
      <webElementGuid>31c613e1-0824-44a4-beae-ee7c25f912fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/input</value>
      <webElementGuid>8289a76b-bbe8-497c-a0b6-ad9a2fba3f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_telp' and @placeholder = 'No Telp' and @name = 'no_telp' and @type = 'number']</value>
      <webElementGuid>ce9554a5-ec76-4e14-a046-acd9fa15c57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
