<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MIG_gwt-Label GDPVGE1BM1</name>
   <tag></tag>
   <elementGuidId>bc4f8408-aff0-484f-b311-63b9d8a9bfa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.gwt-Label.GDPVGE1BM1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5b9f684aaf0f4897b59b7edf00c52cc4']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;MMSGI&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53dd6e6b-a769-4438-b6a7-d90601e28d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Label GDPVGE1BM1</value>
      <webElementGuid>145ddf6e-dec6-49e3-a2d6-13f34d599d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>authSelectorOptionLabel</value>
      <webElementGuid>3565a003-a1d2-4fb0-b696-2c817d6a57c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MMSGI</value>
      <webElementGuid>2ba7fe8e-4a22-45e0-81dd-e3b3a1150218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5b9f684aaf0f4897b59b7edf00c52cc4&quot;)/div[@class=&quot;GDPVGE1BJ1&quot;]/div[@class=&quot;GDPVGE1BL1&quot;]/div[@class=&quot;gwt-Label GDPVGE1BM1&quot;]</value>
      <webElementGuid>f3858be9-1bda-443d-8048-83ab3c5d682b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5b9f684aaf0f4897b59b7edf00c52cc4']/div/div/div</value>
      <webElementGuid>6b380e08-d22f-4f19-a826-2c784a22e1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIG'])[1]/preceding::div[4]</value>
      <webElementGuid>b774a0b7-ed51-4b28-b0c8-b2751cb43cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notice to Users'])[1]/preceding::div[11]</value>
      <webElementGuid>a111603f-1bc9-4d21-8b1e-bedad9e3cb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MMSGI']/parent::*</value>
      <webElementGuid>816e86ee-637d-4a75-8123-a38b76ca5f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>be4d08ce-d4f2-41fc-994a-4d7184b69da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MMSGI' or . = 'MMSGI')]</value>
      <webElementGuid>da86ecfb-983f-4d80-a87e-c5c24a5ed144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
