<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Workflow Type</name>
   <tag></tag>
   <elementGuidId>26e466f7-0696-4f58-9260-27333c30f132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboWorkflowType_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cboWorkflowType_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboWorkflowType_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9221522-fbcc-4a9d-b4a0-216e45098549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>7965d796-3dd4-44b5-889c-ac75deda9a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboWorkflowType_I</value>
      <webElementGuid>3fac2a3a-f601-419b-b450-b5208d62df6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cboWorkflowType</value>
      <webElementGuid>debf27dd-2d93-494a-84f2-9df5cbffa8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('cboWorkflowType')</value>
      <webElementGuid>b6c0c733-56b7-4e73-aebc-6d7831949f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-- Please select --</value>
      <webElementGuid>2e3e6475-ed58-44d6-9d1b-024382ba7922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ccef1be-85ae-46ab-b3f7-60db292e2392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e46d4857-11de-4a0f-9a10-98eabc0d4d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboWorkflowType_I&quot;)</value>
      <webElementGuid>8b4fa479-3e88-4289-9bcb-44179de3956d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cboWorkflowType_I']</value>
      <webElementGuid>d7c5a5c0-0e80-4601-bc13-4239da81a1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cboWorkflowType']/tbody/tr/td[2]/input</value>
      <webElementGuid>18887bb6-fef0-46b1-ab39-6475e48bc0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>006ad854-ef0b-4b35-a2a2-f185591a1ee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cboWorkflowType_I' and @name = 'cboWorkflowType' and @type = 'text']</value>
      <webElementGuid>f78c6240-45e3-457f-842a-b014948e3907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
