<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show_OrgStructure</name>
   <tag></tag>
   <elementGuidId>0938c608-5a23-4adb-bf2a-df62022154b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboOrgStructure_I</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cboOrgStructure_I']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cboOrgStructure_I</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50f275dc-b5da-472d-be2d-4911a1f8868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxeEditArea_MetropolisBlue dxeEditAreaSys dxh0</value>
      <webElementGuid>caac8b96-b50a-451a-8bf4-f8bfbcbd88ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboOrgStructure_I</value>
      <webElementGuid>fe9f04df-0df3-409a-ac40-e67f23632c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cboOrgStructure</value>
      <webElementGuid>4167501a-c50f-4189-89b7-6aa67fb523a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ASPx.ETextChanged('cboOrgStructure')</value>
      <webElementGuid>afa2f11f-06d2-4e2a-b66e-690ef9c55179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Employee Code</value>
      <webElementGuid>c25b6c70-9f45-49ec-a672-491d10d3de9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33b9c980-a62a-4cc5-85b4-ea6714cc5ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea668a76-4a9a-4823-8b7b-8c217f4b2700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboOrgStructure_I&quot;)</value>
      <webElementGuid>526adc84-c443-4561-b72c-68a289aa9ebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cboOrgStructure_I']</value>
      <webElementGuid>35310dcb-6a4b-4d85-aeaa-da37efc1376a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cboOrgStructure']/tbody/tr/td[2]/input</value>
      <webElementGuid>9fce7ca2-0611-4b27-bacf-b89072f22610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>781101c0-fa96-42f8-a9ea-0f3f6f622ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cboOrgStructure_I' and @name = 'cboOrgStructure' and @type = 'text']</value>
      <webElementGuid>54973fbf-f126-4d13-ab2b-089c10214848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
