<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Open_Workflow Type</name>
   <tag></tag>
   <elementGuidId>47687cea-aa42-4ff9-ac88-687ac8627f51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboWorkflowType_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cboWorkflowType_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;v -- Please select -- Acknowledgement Claim Application Clocking Application Daily Attendance Exit Application Exit Interview Hiring Interview&quot;i] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0fab600-9de9-42c7-8b11-0f2efa02ca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboWorkflowType_B-1Img</value>
      <webElementGuid>fd66fc0e-6809-4998-84a4-1e86b1d37fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_MetropolisBlue</value>
      <webElementGuid>5fe53e57-1ac3-4d72-b966-a85d33f9d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MMSGI/DXR.axd?r=1_87-7Zbav</value>
      <webElementGuid>d93fab79-e93c-4194-a2fe-23ac86124ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>e27bf844-eb64-4eb2-8fc0-ab752d1be9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboWorkflowType_B-1Img&quot;)</value>
      <webElementGuid>e50d2b87-1b05-43fd-bf64-b4d787a9b278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cboWorkflowType_B-1Img']</value>
      <webElementGuid>9b211f47-8b1b-442d-9e6a-8bf1fa3dc325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cboWorkflowType_B-1']/img</value>
      <webElementGuid>10cad112-cd0f-4b63-be76-d0983095923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='v']</value>
      <webElementGuid>efd0bf04-31fe-4cc2-9832-7ee4f09e6cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/img</value>
      <webElementGuid>90b829ad-e44f-4497-aa4a-a38df1a0d4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cboWorkflowType_B-1Img' and @src = '/MMSGI/DXR.axd?r=1_87-7Zbav' and @alt = 'v']</value>
      <webElementGuid>0e96c8f2-bad4-4249-8992-7cc0544ee580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
