<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Open_cboOrgStructure</name>
   <tag></tag>
   <elementGuidId>ccff7f2c-e2b3-4714-b807-c24a73461f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cboOrgStructure_B-1Img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cboOrgStructure_B-1Img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;v -- Please select -- Employee Code Company Department Cost Center Designation Employment Type Location Alias Name Local Name&quot;i] >> internal:attr=[alt=&quot;v&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7622c912-3791-4545-8ef4-675d2fdffbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cboOrgStructure_B-1Img</value>
      <webElementGuid>845472fe-b461-4239-a642-bcfa571e64e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dxEditors_edtDropDown_MetropolisBlue</value>
      <webElementGuid>b2f48278-f76a-44e0-8db1-6a0675990392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/MMSGI/DXR.axd?r=1_87-7Zbav</value>
      <webElementGuid>ad21a457-2e66-4659-aa90-79fbbf5bb5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>v</value>
      <webElementGuid>4749ce75-4f62-4e54-9108-8c5077819a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cboOrgStructure_B-1Img&quot;)</value>
      <webElementGuid>cf3be0c8-9c96-4d53-968c-83d5588b07ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cboOrgStructure_B-1Img']</value>
      <webElementGuid>906eda4e-1361-40e5-893d-f40fd56b9416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cboOrgStructure_B-1']/img</value>
      <webElementGuid>d5df7cf7-a1e1-48ae-9588-6413ef9c272d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='v'])[2]</value>
      <webElementGuid>c134da03-fdec-40d9-bfbd-4180691bde22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td[3]/img</value>
      <webElementGuid>18cab250-c9fe-4863-8c58-976321c2ee43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cboOrgStructure_B-1Img' and @src = '/MMSGI/DXR.axd?r=1_87-7Zbav' and @alt = 'v']</value>
      <webElementGuid>f9308595-a113-4fbd-b910-0c97189fcf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
