<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose_vendor_data</name>
   <tag></tag>
   <elementGuidId>9536d51d-07d6-48e6-8917-cc71e0e3eda7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='choose_vendor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;choose_vendor&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c14fe29-4c7b-4d32-b391-37edb021ecf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>afa99628-913a-4434-9fcf-f55026ebec5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ca614423-1551-4af8-80a4-f6533dc70ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choose_vendor</value>
      <webElementGuid>e6ff91d7-f7d1-403f-97eb-94d6b142bd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ccc0a305-667e-44fe-9101-704081e4f956</value>
      <webElementGuid>f969f4fa-e7f9-4b41-8f97-ce94edc59a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_search_vendor&quot;)/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>c6bdc484-bc56-45b5-ac0c-b86b9669105d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='choose_vendor']</value>
      <webElementGuid>76e7cb03-619c-4cfb-aedc-2a26398bd1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table_search_vendor']/tbody/tr/td[4]/input</value>
      <webElementGuid>b4fe355e-6e9f-41ef-a2af-695f462f4903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>914d188b-bcfa-4255-b4bf-fdd66ac59cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'choose_vendor']</value>
      <webElementGuid>be1c541e-3f35-4206-a4c2-9a570a58bd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
