<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vendor_id_text</name>
   <tag></tag>
   <elementGuidId>b1d4522d-e553-450a-a3bb-41173bc35283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vendor_id_text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vendor_id_text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill input Vendor Name...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d80d390-7ecf-4dd1-9c55-39da98b74c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid  </value>
      <webElementGuid>8e2c4a29-4efa-48d6-a2bf-491ed992dd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>1a36e194-add8-4e32-a554-bad3e1ecca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vendor_id_text</value>
      <webElementGuid>98190ed8-fd71-4078-933f-a4c4e25c427e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill input Vendor Name...</value>
      <webElementGuid>01655917-c1d6-4521-8f68-f94bd534eb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-msg-required</name>
      <type>Main</type>
      <value>Required Fields</value>
      <webElementGuid>f046a6bc-e893-42f5-b102-7bc663351b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vendor_id_text</value>
      <webElementGuid>1a741d0d-d880-4f5a-8676-643f222540ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc6be0fd-10bd-42d0-a26d-a5315d3c67d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vendor_id_text&quot;)</value>
      <webElementGuid>f5617b80-3f59-468c-9b41-1f8dd929f7af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vendor_id_text']</value>
      <webElementGuid>74ea68a6-dffc-42c7-9256-c338fe45d196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='purchase_order']/div/div/div[2]/div[4]/input[2]</value>
      <webElementGuid>3ac60148-43e6-4ccb-b83a-8a2a8d23f92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input[2]</value>
      <webElementGuid>ff63953e-cf52-49ff-a0c7-111c621a6a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'vendor_id_text' and @placeholder = 'Fill input Vendor Name...' and @name = 'vendor_id_text' and @type = 'text']</value>
      <webElementGuid>e9094e49-4d1c-4fa1-8db7-303158ee25bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
