<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select Shipping Address</name>
   <tag></tag>
   <elementGuidId>4079e4b2-4572-4062-9094-263e039f646e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;purchase_order&quot;]/div/div[1]/div[2]/div[6]/span/span[1]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-shipping_address-container > span.select2-selection__placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Select Shipping Address...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73fb4ec2-5e15-45cc-9634-d4b6ca4ac2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__placeholder</value>
      <webElementGuid>21b07713-aa7b-4f65-becf-8f2f6e80800e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Shipping Address...</value>
      <webElementGuid>5774fec4-b08c-49c6-bd1e-8e2d205e0c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-shipping_address-container&quot;)/span[@class=&quot;select2-selection__placeholder&quot;]</value>
      <webElementGuid>62b92c0a-01c3-46f3-bac9-02eed60644d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='select2-shipping_address-container']/span</value>
      <webElementGuid>de91e1f0-6981-4ce2-83a2-1fe319342425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::span[5]</value>
      <webElementGuid>71ceb2c0-6ee5-468f-89f3-13b77e7c84d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/preceding::span[3]</value>
      <webElementGuid>52c9438c-f46e-430b-93f8-12564d00feaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/preceding::span[3]</value>
      <webElementGuid>02676169-c1f6-4690-8437-8da0b2250001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Shipping Address...']/parent::*</value>
      <webElementGuid>8ed8d39b-f6bb-4497-8038-653f0c7e5837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/span/span/span/span</value>
      <webElementGuid>ecee4d3a-d4c5-46ad-8f86-5e26a19ba426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Shipping Address...' or . = 'Select Shipping Address...')]</value>
      <webElementGuid>e039a01f-a760-4769-956e-806ecf385373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
