<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Registration Approval_modules</name>
   <tag></tag>
   <elementGuidId>4540c4b4-0673-4ae6-99ea-f557a2192695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='modules[]'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(22) > .checkbox2 > .checkbox-menu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b81a5c0-4d85-4e50-88f8-b5e1362eab6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a4e01701-db2f-4b48-982e-4ec3debd6011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-menu</value>
      <webElementGuid>50f15ae4-0c71-453a-9799-aeecf73b9031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Vendor Registration Approval</value>
      <webElementGuid>746c7e58-ebe4-4112-b718-07270a735270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modules[]</value>
      <webElementGuid>97bd96e6-608d-4f60-9c82-f00f4da2540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delegation&quot;)/div[@class=&quot;card mb-10&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row content-tab-home mt-4&quot;]/div[@class=&quot;col-md-12 mb-4&quot;]/label[@class=&quot;checkbox2 path&quot;]/input[@class=&quot;checkbox-menu&quot;]</value>
      <webElementGuid>d212d56e-3cb8-4ff1-9818-00dc1edd3389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='modules[]'])[7]</value>
      <webElementGuid>abe00f88-c1d5-432e-9c3e-2528a0a9a1e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='delegation']/div/div/div/div[14]/label/input</value>
      <webElementGuid>214844a6-be8a-45e2-b8e3-a5adb4338122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/label/input</value>
      <webElementGuid>59e8c5d8-1730-4593-a4d0-aec81d657166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'modules[]']</value>
      <webElementGuid>8123f3ba-b48c-4b0a-8ce1-f0cc5bcb4f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
