<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Registration Exceptional_modules</name>
   <tag></tag>
   <elementGuidId>9230c26c-7e5a-471a-93a5-afed51ae5f89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='modules[]'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(23) > .checkbox2 > .checkbox-menu</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a73d9f79-aafc-4dfb-a306-0ccb920c0e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e2ef5837-de8d-445e-a5f8-2acadb66fbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-menu</value>
      <webElementGuid>a023dcb4-aff7-4135-9711-f4bb2ae17479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Vendor Registration Exceptional</value>
      <webElementGuid>c48cb706-08bb-47c5-acbe-c03dc862d69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modules[]</value>
      <webElementGuid>118c2d00-cf0c-450e-a913-b46492143403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delegation&quot;)/div[@class=&quot;card mb-10&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row content-tab-home mt-4&quot;]/div[@class=&quot;col-md-12 mb-4&quot;]/label[@class=&quot;checkbox2 path&quot;]/input[@class=&quot;checkbox-menu&quot;]</value>
      <webElementGuid>a4a5ed05-dc09-4132-bb4a-b64f64aa1be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='modules[]'])[8]</value>
      <webElementGuid>e4233a1e-0b78-4823-8a45-828b7a3aac92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='delegation']/div/div/div/div[15]/label/input</value>
      <webElementGuid>cf6c1a8f-0e5c-46e9-8a77-5b5ae126eb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/label/input</value>
      <webElementGuid>e882803f-5bfd-48c9-b737-18cd2afe225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'modules[]']</value>
      <webElementGuid>50020c04-bc48-49d5-ba3c-f0386031f8f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
