<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_type_business_field</name>
   <tag></tag>
   <elementGuidId>a4f6939a-7952-4c5f-a310-cd69a3f08ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_modal_new_address_scroll']/div[4]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection.select2-selection--single.col-md-6.form-select.form-select-solid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select Type...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>01085f66-516c-48a4-9209-ff815359c554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single col-md-6 form-select form-select-solid</value>
      <webElementGuid>de67cffd-2263-4f7f-b24a-59cfdb0039d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>16ad5195-c845-4cc5-af9e-4ef08298635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>789ad81c-6d95-405d-a998-4f421a5b5fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c073e951-5327-4a9d-bba0-dcb83ec5571e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>040d2b27-d0de-4a5a-aad1-3cf5b3a8459c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1313e874-2fd6-4af7-af08-381e50958065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-type-container</value>
      <webElementGuid>0b2fa6ed-740f-4e25-9260-bb291d17cbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-type-container</value>
      <webElementGuid>9e7b9381-9931-450f-b214-7e8c2c14b9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-type-results</value>
      <webElementGuid>11ad9b26-7401-45e5-9f7f-e0ea4f7ff5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>select2-type-result-4nr9-BU</value>
      <webElementGuid>b4a7af0b-08eb-456d-9043-2860f93e65e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Type...</value>
      <webElementGuid>b1d838cf-0253-4f8a-aa21-112099afc21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_new_address_scroll&quot;)/div[@class=&quot;col-md-6 d-flex flex-column mb-9 fv-row box_type&quot;]/span[@class=&quot;select2 select2-container select2-container--bootstrap5 select2-container--below select2-container--open select2-container--focus&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single col-md-6 form-select form-select-solid&quot;]</value>
      <webElementGuid>a0f76376-d1d8-44ad-b790-373c92ca67ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_new_address_scroll']/div[4]/span/span/span</value>
      <webElementGuid>5fd93263-69c2-4658-ab52-edd937acb6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[3]</value>
      <webElementGuid>016225a1-4818-4b2e-b0ca-318e3f8405d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/span/span/span</value>
      <webElementGuid>4d316c86-8574-42e6-9175-084ade9c1f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Type...' or . = 'Select Type...')]</value>
      <webElementGuid>53bb4361-1e3d-4c3b-80ce-abdbddf3ef2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
