<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supporting Document_supporting_document</name>
   <tag></tag>
   <elementGuidId>dd677207-e475-4244-a7de-cf4a18fe7165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supporting_document_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#supporting_document_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#supporting_document_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2adeef5e-64fe-484c-bda5-023e6d3ae443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>cd3c474e-02d5-4ef4-9a64-228bc96441f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input</value>
      <webElementGuid>8f3d8350-145d-4fc5-a8f5-b6f08f67c200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supporting_document[]</value>
      <webElementGuid>e11f077f-cce3-47b9-9614-6e69f76f0905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supporting_document_1</value>
      <webElementGuid>05a72be4-c9be-4a34-a699-a881fa4389d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supporting_document_1&quot;)</value>
      <webElementGuid>6ccfbe45-dfd2-4e4e-9fca-6cfd79c50e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supporting_document_1']</value>
      <webElementGuid>5179510c-19f7-4c65-9f61-db5696cdd483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_supporting_document_1']/div/div/input</value>
      <webElementGuid>cee702cb-0488-4cc5-9424-97c9e9ca5b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>d32b144d-84e7-40d6-8c25-72c7a0a1df80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'supporting_document[]' and @id = 'supporting_document_1']</value>
      <webElementGuid>a7c36f14-a21c-46b2-b715-b7c84a09eb9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
