<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Created At_created_at</name>
   <tag></tag>
   <elementGuidId>ad1b816c-5974-4464-a965-051f2e039cb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#created_at</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='created_at']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#created_at</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f35e03d7-0f5a-4f09-b798-df02ac465cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b9ba519-2bfc-4945-8a3b-291daf834f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>created_at</value>
      <webElementGuid>62577761-cb1e-4b87-8939-66b348e3267e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-solid ps-12 </value>
      <webElementGuid>34b75307-9cfe-4fdd-9d35-2141d7c567a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>056da72e-abe2-4097-a9d0-e8aa7ac4ab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>created_at</value>
      <webElementGuid>e3997a57-7b49-4b35-897f-709e92a528b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-id</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>10f3df32-8bae-4814-8615-8a16b532f8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;created_at&quot;)</value>
      <webElementGuid>860d190f-98a0-4641-8141-c250d817f6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='created_at']</value>
      <webElementGuid>fe69ebb7-1485-43db-af27-a4dde6e61c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_add_item_scroll']/div/div/div/div[16]/div/input</value>
      <webElementGuid>e434690d-3c4c-45bb-bde7-68656c294228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>e9343c8e-937c-49cc-81d6-f57029403751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'created_at' and @placeholder = 'Select a date' and @name = 'created_at']</value>
      <webElementGuid>fed9cac5-81cf-40e5-ad7f-510d9eb348f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
